name: Update volume_accumulate_and_sector.ipynb
on:
  schedule:
    - cron: '1 1 * * *'
  workflow_dispatch:
jobs:
  update_scripts:
    name: update ascii tables with data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Script and Update Tables
        run: |
          jupyter nbconvert --to script volume_accumulation_and_sector.ipynb
          python volume_accumulation_and_sector.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update"
          git push
